-- Tabelas do projeto DONKI-FLR. Execute no SQL Editor do Supabase.
create table if not exists public.flares (
    id bigint generated by default as identity primary key,
    flr_id text not null,
    catalog text,
    begin_time timestamptz,
    peak_time timestamptz,
    end_time timestamptz,
    class_type text,
    source_location text,
    active_region_num integer,
    submission_time timestamptz,
    note text,
    link text,
    instruments jsonb not null default '[]'::jsonb,
    linked_events jsonb not null default '[]'::jsonb,
    raw_payload jsonb not null default '{}'::jsonb,
    collected_at timestamptz not null default now(),
    constraint flares_flr_id_key unique (flr_id)
);

create table if not exists public.execucoes (
    id bigint generated by default as identity primary key,
    iniciado_em timestamptz not null,
    finalizado_em timestamptz not null,
    registros_processados integer not null default 0,
    lotes integer not null default 0,
    erros jsonb not null default '[]'::jsonb,
    status text not null check (status in ('concluido', 'erro_parcial', 'erro_critico'))
);

create index if not exists flares_begin_time_idx on public.flares (begin_time desc);
create index if not exists flares_class_type_idx on public.flares (class_type);
create index if not exists execucoes_finalizado_em_idx on public.execucoes (finalizado_em desc);

alter table public.flares enable row level security;
alter table public.execucoes enable row level security;

drop policy if exists "Public can read flares" on public.flares;
create policy "Public can read flares" on public.flares
    for select to anon, authenticated using (true);

drop policy if exists "Public can read execucoes" on public.execucoes;
create policy "Public can read execucoes" on public.execucoes
    for select to anon, authenticated using (true);

grant select on public.flares to anon, authenticated;
grant select on public.execucoes to anon, authenticated;
grant all on public.flares to service_role;
grant all on public.execucoes to service_role;
grant usage, select on all sequences in schema public to service_role;
